import { useMemo } from 'react';
import { StyleSheet } from 'react-native';
import { fonts } from '@jotbunker/shared';
import { useTheme } from '../../hooks/useTheme';

export function useSettingsStyles() {
  const { colors, confirmDialog: dialog, settingsPanel: sp } = useTheme();
  const styles = useMemo(() => StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: dialog.overlayBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    box: {
      backgroundColor: colors.dialogBg,
      borderWidth: 1,
      borderColor: colors.dialogBorder,
      borderRadius: dialog.boxRadius,
      paddingVertical: dialog.boxPaddingV,
      paddingHorizontal: dialog.boxPaddingH,
      width: sp.boxWidth,
      maxHeight: sp.maxHeight,
      alignItems: 'center',
      gap: dialog.boxGap,
    },
    logoArea: {
      alignItems: 'center',
      marginBottom: 16,
    },
    logoIcon: {
      width: 72,
      height: 72,
      borderRadius: 14,
      marginBottom: 8,
    },
    logoText: {
      fontFamily: `${fonts.sans}-Bold`,
      fontSize: 14,
      color: colors.textPrimary,
      letterSpacing: 1.5,
      opacity: 0.6,
    },
    logoSubtext: {
      fontFamily: `${fonts.sans}-Regular`,
      fontSize: 11,
      color: colors.textPrimary,
      letterSpacing: 0.5,
      opacity: 0.4,
      marginTop: 2,
    },
    title: {
      fontFamily: `${fonts.sans}-Black`,
      fontSize: dialog.titleFontSize + 12,
      color: colors.textPrimary,
      letterSpacing: (dialog.titleFontSize + 12) * dialog.titleLetterSpacing,
      textAlign: 'center',
      marginBottom: sp.titleMarginBottom,
    },
    divider: {
      height: 1,
      backgroundColor: colors.dialogBorder,
      width: '100%',
      marginBottom: 20,
    },
    section: {
      marginBottom: 20,
      width: '100%',
    },
    sectionLabel: {
      fontFamily: `${fonts.sans}-Bold`,
      fontSize: sp.sectionLabelFontSize + 2,
      letterSpacing: (sp.sectionLabelFontSize + 2) * sp.sectionLabelLetterSpacing,
      color: sp.sectionLabelColor,
      textAlign: 'center',
      marginBottom: sp.sectionLabelMarginBottom,
    },
    statusRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      marginBottom: 8,
    },
    statusDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    statusDotOn: {
      backgroundColor: '#4ade80',
    },
    statusDotOff: {
      backgroundColor: colors.textUltraDim,
    },
    statusText: {
      fontFamily: `${fonts.mono}-Bold`,
      fontSize: 11,
      letterSpacing: 1,
    },
    statusTextOn: {
      color: '#4ade80',
    },
    statusTextOff: {
      color: colors.textUltraDim,
    },
    scanBtn: {
      alignSelf: 'center',
      paddingVertical: 10,
      paddingHorizontal: 24,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.primary,
      marginBottom: 14,
    },
    scanBtnText: {
      fontFamily: `${fonts.sans}-Bold`,
      fontSize: 12,
      letterSpacing: 12 * 0.1,
      color: colors.primary,
    },
    inputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: sp.rowGap,
      marginBottom: sp.rowMarginBottom,
    },
    syncLabel: {
      fontFamily: `${fonts.mono}-Bold`,
      fontSize: sp.rowNumFontSize,
      color: sp.rowNumColor,
      width: 90,
      textAlign: 'right',
    },
    syncInput: {
      flex: 1,
      backgroundColor: sp.inputBg,
      borderWidth: 1,
      borderColor: sp.inputBorder,
      borderRadius: sp.inputRadius,
      paddingVertical: sp.inputPaddingV,
      paddingHorizontal: sp.inputPaddingH,
      color: colors.textPrimary,
      fontFamily: `${fonts.sans}-Bold`,
      fontSize: sp.inputFontSize,
      letterSpacing: sp.inputFontSize * sp.inputLetterSpacing,
    },
    portInput: {
      width: 64,
      backgroundColor: sp.inputBg,
      borderWidth: 1,
      borderColor: sp.inputBorder,
      borderRadius: sp.inputRadius,
      paddingVertical: sp.inputPaddingV,
      paddingHorizontal: sp.inputPaddingH,
      color: colors.textPrimary,
      fontFamily: `${fonts.sans}-Bold`,
      fontSize: sp.inputFontSize,
      letterSpacing: sp.inputFontSize * sp.inputLetterSpacing,
    },
    rowNum: {
      fontFamily: `${fonts.mono}-Bold`,
      fontSize: sp.rowNumFontSize,
      color: sp.rowNumColor,
      width: sp.rowNumWidth,
      textAlign: 'right',
    },
    input: {
      flex: 1,
      backgroundColor: sp.inputBg,
      borderWidth: 1,
      borderColor: sp.inputBorder,
      borderRadius: sp.inputRadius,
      paddingVertical: sp.inputPaddingV,
      paddingHorizontal: sp.inputPaddingH,
      color: colors.textPrimary,
      fontFamily: `${fonts.sans}-Bold`,
      fontSize: sp.inputFontSize,
      letterSpacing: sp.inputFontSize * sp.inputLetterSpacing,
    },
    btnRow: {
      flexDirection: 'row',
      gap: dialog.btnGap,
      width: '100%',
    },
    cancelBtn: {
      flex: 1,
      paddingVertical: dialog.btnPaddingV,
      borderRadius: dialog.btnRadius,
      backgroundColor: dialog.cancelBg,
      borderWidth: 1,
      borderColor: dialog.cancelBorder,
      alignItems: 'center',
    },
    cancelText: {
      fontFamily: `${fonts.sans}-Bold`,
      fontSize: dialog.btnFontSize,
      letterSpacing: dialog.btnFontSize * dialog.btnLetterSpacing,
      color: colors.primary,
    },
    saveBtn: {
      flex: 1,
      paddingVertical: dialog.btnPaddingV,
      borderRadius: dialog.btnRadius,
      backgroundColor: sp.saveBg,
      borderWidth: 1,
      borderColor: sp.saveBorder,
      alignItems: 'center',
    },
    saveText: {
      fontFamily: `${fonts.sans}-Bold`,
      fontSize: dialog.btnFontSize,
      letterSpacing: dialog.btnFontSize * dialog.btnLetterSpacing,
      color: colors.primary,
    },
    accessory: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      backgroundColor: colors.dialogBg,
      borderTopWidth: 1,
      borderTopColor: colors.dialogBorder,
      paddingHorizontal: 16,
      paddingVertical: 8,
    },
    doneBtn: {
      backgroundColor: colors.dialogBorder,
      borderWidth: 1,
      borderColor: colors.textUltraDim,
      paddingVertical: 6,
      paddingHorizontal: 16,
      borderRadius: 6,
    },
    doneBtnText: {
      fontFamily: `${fonts.sans}-Bold`,
      fontSize: 12,
      letterSpacing: 12 * 0.08,
      color: colors.primary,
    },
    unpairBtn: {
      alignSelf: 'center',
      paddingVertical: 8,
      paddingHorizontal: 20,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.textUltraDim,
      marginTop: 10,
    },
    unpairBtnText: {
      fontFamily: `${fonts.sans}-Bold`,
      fontSize: 11,
      letterSpacing: 11 * 0.1,
      color: colors.textSecondary,
    },
    modifyBtn: {
      alignSelf: 'center',
      paddingVertical: sp.pillPaddingV,
      paddingHorizontal: sp.pillPaddingH,
      borderRadius: sp.pillRadius,
      backgroundColor: sp.pillBg,
      borderWidth: 1,
      borderColor: sp.pillBorder,
      marginTop: 8,
    },
    modifyBtnText: {
      fontFamily: `${fonts.sans}-Bold`,
      fontSize: sp.pillFontSize,
      letterSpacing: sp.pillFontSize * sp.pillLetterSpacing,
      color: colors.primary,
    },
    collapsedSummary: {
      fontFamily: `${fonts.mono}-Bold`,
      fontSize: 12,
      color: colors.textSecondary,
      textAlign: 'center',
      marginBottom: 4,
    },
  }), [colors, dialog, sp]);
  return { colors, dialog, sp, styles };
}

export type SettingsStyles = ReturnType<typeof useSettingsStyles>;
